{% set name = "mystmd" %}
{% set version = "1.1.33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mystmd-{{ version }}.tar.gz
  sha256: 9830e4a0a43304fd3e22a9e9ec68d74e03568988679d11bc5d92d1460f9717d7

build:
  entry_points:
    - myst = mystmd_py.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - mystmd_py
  commands:
    - pip check
    - myst --help
  requires:
    - pip
    - nodejs

about:
  home: https://github.com/executablebooks/mystmd
  summary: Command line tools for MyST Markdown
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fwkoch
    - rowanc1
