{% set name = "mystmd" %}
{% set version = "1.3.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mystmd-{{ version }}.tar.gz
  sha256: e1b631fab44a4d7cb96dc399acc515c6cf50d211389a28d5d818e6dcad65abbb

build:
  entry_points:
    - myst = mystmd_py.main:main
  noarch: python
  script_env:
    - MYSTMD_PACKAGE_VARIANT=conda-forge
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
    - hatch-nodejs-version
    - hatch-deps-selector
  run:
    - python >=3.8
    - nodejs >=18

test:
  imports:
    - mystmd_py
  commands:
    - pip check
    - myst --help
  requires:
    - pip
    - nodejs >=18

about:
  home: https://github.com/executablebooks/mystmd
  summary: Command line tools for MyST Markdown
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - agoose77
    - fwkoch
    - rowanc1
