{% set name = "mystmd" %}
{% set version = "1.3.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mystmd-{{ version }}.tar.gz
  sha256: dd2a9e92e52d943648d163d826d185e3f591f7b749aeeae11ed049000b52380b

build:
  entry_points:
    - myst = mystmd_py.main:main
  noarch: python
  script_env:
    - MYSTMD_PACKAGE_VARIANT=conda-forge
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-nodejs-version
    - hatch-deps-selector
  run:
    - python >={{ python_min }}
    - nodejs >=18

test:
  imports:
    - mystmd_py
  commands:
    - pip check
    - myst --help
  requires:
    - pip
    - nodejs >=18
    - python {{ python_min }}

about:
  home: https://github.com/executablebooks/mystmd
  summary: Command line tools for MyST Markdown
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - agoose77
    - fwkoch
    - rowanc1
